/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/

var __defProp = Object.defineProperty;
var __getOwnPropDesc = Object.getOwnPropertyDescriptor;
var __getOwnPropNames = Object.getOwnPropertyNames;
var __hasOwnProp = Object.prototype.hasOwnProperty;
var __export = (target, all) => {
  for (var name in all)
    __defProp(target, name, { get: all[name], enumerable: true });
};
var __copyProps = (to, from, except, desc) => {
  if (from && typeof from === "object" || typeof from === "function") {
    for (let key of __getOwnPropNames(from))
      if (!__hasOwnProp.call(to, key) && key !== except)
        __defProp(to, key, { get: () => from[key], enumerable: !(desc = __getOwnPropDesc(from, key)) || desc.enumerable });
  }
  return to;
};
var __toCommonJS = (mod) => __copyProps(__defProp({}, "__esModule", { value: true }), mod);

// main.ts
var main_exports = {};
__export(main_exports, {
  default: () => ANAPlugin
});
module.exports = __toCommonJS(main_exports);
var import_obsidian3 = require("obsidian");

// api.ts
var ANAApiClient = class {
  constructor(baseUrl) {
    this.baseUrl = baseUrl.replace(/\/$/, "");
  }
  async checkStatus() {
    try {
      const response = await fetch(`${this.baseUrl}/api/status`);
      return response.ok;
    } catch (e) {
      return false;
    }
  }
  async processNote(content, frontmatter, title) {
    const response = await fetch(`${this.baseUrl}/api/process`, {
      method: "POST",
      headers: { "Content-Type": "application/json" },
      body: JSON.stringify({ content, frontmatter, title })
    });
    if (!response.ok) {
      const error = await response.text();
      throw new Error(`API error: ${error}`);
    }
    return await response.json();
  }
  async answerQuestions(sessionId, answers) {
    const response = await fetch(`${this.baseUrl}/api/answer`, {
      method: "POST",
      headers: { "Content-Type": "application/json" },
      body: JSON.stringify({ session_id: sessionId, answers })
    });
    if (!response.ok) {
      const error = await response.text();
      throw new Error(`API error: ${error}`);
    }
    return await response.json();
  }
  async saveNote(sessionId, outputPath, overwrite = false) {
    const response = await fetch(`${this.baseUrl}/api/save`, {
      method: "POST",
      headers: { "Content-Type": "application/json" },
      body: JSON.stringify({
        session_id: sessionId,
        output_path: outputPath,
        overwrite
      })
    });
    if (!response.ok) {
      const error = await response.text();
      throw new Error(`API error: ${error}`);
    }
    return await response.json();
  }
  async deleteSession(sessionId) {
    await fetch(`${this.baseUrl}/api/session/${sessionId}`, {
      method: "DELETE"
    });
  }
};

// settings.ts
var import_obsidian = require("obsidian");
var DEFAULT_SETTINGS = {
  serverUrl: "http://127.0.0.1:8765",
  autoSave: false,
  showPreview: true,
  maxQuestions: 5
};
var ANASettingTab = class extends import_obsidian.PluginSettingTab {
  constructor(app, plugin) {
    super(app, plugin);
    this.plugin = plugin;
  }
  display() {
    const { containerEl } = this;
    containerEl.empty();
    containerEl.createEl("h2", { text: "ANA - Atomic Note Architect" });
    containerEl.createEl("p", {
      text: "AI\uB97C \uC0AC\uC6A9\uD558\uC5EC \uC6D0\uC2DC \uB178\uD2B8\uB97C Zettelkasten \uC2A4\uD0C0\uC77C Atomic Note\uB85C \uBCC0\uD658\uD569\uB2C8\uB2E4.",
      cls: "setting-item-description"
    });
    new import_obsidian.Setting(containerEl).setName("Server URL").setDesc('ANA API \uC11C\uBC84 \uC8FC\uC18C (\uD130\uBBF8\uB110\uC5D0\uC11C "ana serve" \uC2E4\uD589 \uD544\uC694)').addText((text) => text.setPlaceholder("http://127.0.0.1:8765").setValue(this.plugin.settings.serverUrl).onChange(async (value) => {
      this.plugin.settings.serverUrl = value;
      await this.plugin.saveSettings();
    }));
    new import_obsidian.Setting(containerEl).setName("Auto Save").setDesc("\uCC98\uB9AC \uC644\uB8CC \uD6C4 \uC790\uB3D9\uC73C\uB85C \uB178\uD2B8 \uC800\uC7A5").addToggle((toggle) => toggle.setValue(this.plugin.settings.autoSave).onChange(async (value) => {
      this.plugin.settings.autoSave = value;
      await this.plugin.saveSettings();
    }));
    new import_obsidian.Setting(containerEl).setName("Show Preview").setDesc("\uC800\uC7A5 \uC804 \uC0DD\uC131\uB41C \uB178\uD2B8 \uBBF8\uB9AC\uBCF4\uAE30 \uD45C\uC2DC").addToggle((toggle) => toggle.setValue(this.plugin.settings.showPreview).onChange(async (value) => {
      this.plugin.settings.showPreview = value;
      await this.plugin.saveSettings();
    }));
    new import_obsidian.Setting(containerEl).setName("Connection Test").setDesc("ANA \uC11C\uBC84 \uC5F0\uACB0 \uD14C\uC2A4\uD2B8").addButton((button) => button.setButtonText("Test Connection").onClick(async () => {
      button.setButtonText("Testing...");
      const isConnected = await this.plugin.apiClient.checkStatus();
      if (isConnected) {
        button.setButtonText("\u2705 Connected");
      } else {
        button.setButtonText("\u274C Failed");
      }
      setTimeout(() => button.setButtonText("Test Connection"), 2e3);
    }));
    containerEl.createEl("h3", { text: "\uC0AC\uC6A9 \uBC29\uBC95" });
    const helpList = containerEl.createEl("ol");
    helpList.createEl("li", { text: '\uD130\uBBF8\uB110\uC5D0\uC11C "ana serve" \uC2E4\uD589' });
    helpList.createEl("li", { text: "\uB178\uD2B8\uB97C \uC5F4\uACE0 Command Palette (Ctrl/Cmd + P) \uC2E4\uD589" });
    helpList.createEl("li", { text: '"ANA: Process Current Note" \uC120\uD0DD' });
    helpList.createEl("li", { text: "\uC9C8\uBB38\uC5D0 \uB2F5\uBCC0\uD558\uC5EC Atomic Note \uC0DD\uC131" });
  }
};

// sidebar.ts
var import_obsidian2 = require("obsidian");
var VIEW_TYPE_ANA = "ana-sidebar-view";
var ANASidebarView = class extends import_obsidian2.ItemView {
  constructor(leaf, plugin) {
    super(leaf);
    this.currentQuestions = [];
    this.currentAnswers = [];
    this.currentQuestionIndex = 0;
    this.onAnswersComplete = null;
    this.plugin = plugin;
  }
  getViewType() {
    return VIEW_TYPE_ANA;
  }
  getDisplayText() {
    return "ANA - Atomic Note Architect";
  }
  getIcon() {
    return "brain";
  }
  async onOpen() {
    const container = this.containerEl.children[1];
    container.empty();
    container.addClass("ana-sidebar");
    const header = container.createEl("div", { cls: "ana-sidebar-header" });
    header.createEl("h4", { text: "\u{1F3DB}\uFE0F ANA" });
    const headerButtons = header.createEl("div", { cls: "ana-header-buttons" });
    const processBtn = headerButtons.createEl("button", {
      text: "\u25B6 Process",
      cls: "ana-btn ana-btn-primary ana-btn-sm"
    });
    processBtn.addEventListener("click", () => this.plugin.processCurrentNote());
    const clearBtn = headerButtons.createEl("button", {
      text: "Clear",
      cls: "ana-btn ana-btn-sm"
    });
    clearBtn.addEventListener("click", () => this.clear());
    this.logContainer = container.createEl("div", { cls: "ana-log-container" });
    this.log("info", 'ANA \uC900\uBE44 \uC644\uB8CC. "Process" \uBC84\uD2BC\uC744 \uD074\uB9AD\uD558\uAC70\uB098 Ctrl+P \u2192 "ANA: Process Current Note"\uB97C \uC2E4\uD589\uD558\uC138\uC694.');
    this.inputContainer = container.createEl("div", { cls: "ana-input-container" });
    this.inputContainer.style.display = "none";
  }
  async onClose() {
  }
  /**
   * Clear the log
   */
  clear() {
    this.logContainer.empty();
    this.inputContainer.style.display = "none";
    this.log("info", "Log cleared.");
  }
  /**
   * Add a log entry
   */
  log(type, content) {
    const entry = this.logContainer.createEl("div", {
      cls: `ana-log-entry ana-log-${type}`
    });
    const time = (/* @__PURE__ */ new Date()).toLocaleTimeString("ko-KR", {
      hour: "2-digit",
      minute: "2-digit",
      second: "2-digit"
    });
    const icons = {
      info: "\u2139\uFE0F",
      success: "\u2705",
      error: "\u274C",
      question: "\u2753",
      answer: "\u{1F4AC}",
      preview: "\u{1F4DD}"
    };
    entry.createEl("span", { text: `[${time}] ${icons[type]} `, cls: "ana-log-time" });
    entry.createEl("span", { text: content });
    this.logContainer.scrollTop = this.logContainer.scrollHeight;
  }
  /**
   * Show analysis results and handle split suggestions
   * Returns selected topics to process (empty means continue with full note)
   */
  async showAnalysis(response) {
    return new Promise((resolve) => {
      this.log("info", "\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501");
      this.log("info", "\u{1F4CA} \uBD84\uC11D \uACB0\uACFC");
      if (response.analysis) {
        this.log("info", `\uCE74\uD14C\uACE0\uB9AC: ${response.analysis.category}`);
        this.log("info", `\uAC10\uC9C0\uB41C \uAC1C\uB150: ${response.analysis.detected_concepts.join(", ") || "None"}`);
        this.log("info", `\uCDA9\uBD84\uD55C \uC815\uBCF4: ${response.analysis.is_sufficient ? "\uC608" : "\uC544\uB2C8\uC624"}`);
        if (response.analysis.should_split && response.analysis.split_suggestions.length > 0) {
          const topics = response.analysis.split_suggestions;
          this.log("info", `\u26A0\uFE0F ${topics.length}\uAC1C\uC758 \uAC1C\uB150\uC774 \uAC10\uC9C0\uB418\uC5C8\uC2B5\uB2C8\uB2E4!`);
          this.log("info", `\uBD84\uB9AC \uC81C\uC548: ${topics.join(", ")}`);
          this.log("info", "\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501");
          this.inputContainer.empty();
          this.inputContainer.style.display = "flex";
          const continueBtn = this.inputContainer.createEl("button", {
            text: "\u25B6 \uC804\uCCB4 \uB178\uD2B8\uB85C \uACC4\uC18D",
            cls: "ana-btn"
          });
          continueBtn.addEventListener("click", () => {
            this.inputContainer.style.display = "none";
            this.log("info", "\uC804\uCCB4 \uB178\uD2B8\uB85C \uACC4\uC18D \uC9C4\uD589...");
            resolve([]);
          });
          const allBtn = this.inputContainer.createEl("button", {
            text: `\u{1F4DD} \uBAA8\uB450 \uBD84\uB9AC (${topics.length}\uAC1C)`,
            cls: "ana-btn ana-btn-primary"
          });
          allBtn.addEventListener("click", () => {
            this.inputContainer.style.display = "none";
            this.log("info", `${topics.length}\uAC1C \uC8FC\uC81C\uB97C \uC21C\uCC28\uC801\uC73C\uB85C \uCC98\uB9AC\uD569\uB2C8\uB2E4...`);
            resolve([...topics]);
          });
          for (const topic of topics) {
            const splitBtn = this.inputContainer.createEl("button", {
              text: `\u{1F4DD} ${topic}`,
              cls: "ana-btn ana-btn-sm"
            });
            splitBtn.addEventListener("click", () => {
              this.inputContainer.style.display = "none";
              this.log("info", `"${topic}" \uC8FC\uC81C\uB9CC \uCC98\uB9AC...`);
              resolve([topic]);
            });
          }
          this.logContainer.scrollTop = this.logContainer.scrollHeight;
          return;
        }
      }
      this.log("info", "\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501");
      resolve([]);
    });
  }
  /**
   * Ask user to continue with next topic
   */
  async askContinueWithNextTopic(nextTopic, remaining) {
    return new Promise((resolve) => {
      this.log("info", "\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501");
      this.log("info", `\u2705 \uD604\uC7AC \uC8FC\uC81C \uC644\uB8CC!`);
      this.log("info", `\uB2E4\uC74C \uC8FC\uC81C: "${nextTopic}" (\uB0A8\uC740 ${remaining}\uAC1C)`);
      this.inputContainer.empty();
      this.inputContainer.style.display = "flex";
      const continueBtn = this.inputContainer.createEl("button", {
        text: `\u25B6 \uB2E4\uC74C: ${nextTopic}`,
        cls: "ana-btn ana-btn-primary"
      });
      continueBtn.addEventListener("click", () => {
        this.inputContainer.style.display = "none";
        this.log("info", `"${nextTopic}" \uCC98\uB9AC \uC2DC\uC791...`);
        resolve(true);
      });
      const stopBtn = this.inputContainer.createEl("button", {
        text: "\u23F9 \uC5EC\uAE30\uC11C \uC911\uB2E8",
        cls: "ana-btn"
      });
      stopBtn.addEventListener("click", () => {
        this.inputContainer.style.display = "none";
        this.log("info", "\uBD84\uB9AC \uCC98\uB9AC \uC911\uB2E8\uB428");
        resolve(false);
      });
      this.logContainer.scrollTop = this.logContainer.scrollHeight;
    });
  }
  /**
   * Show questions and get answers
   */
  async askQuestions(questions) {
    return new Promise((resolve) => {
      this.currentQuestions = questions;
      this.currentAnswers = new Array(questions.length).fill("");
      this.currentQuestionIndex = 0;
      this.onAnswersComplete = resolve;
      this.log("info", `
\u{1F914} ${questions.length}\uAC1C\uC758 \uC9C8\uBB38\uC5D0 \uB2F5\uD574\uC8FC\uC138\uC694:`);
      this.showNextQuestion();
    });
  }
  showNextQuestion() {
    if (this.currentQuestionIndex >= this.currentQuestions.length) {
      this.inputContainer.style.display = "none";
      this.log("success", "\uBAA8\uB4E0 \uC9C8\uBB38\uC5D0 \uB2F5\uBCC0 \uC644\uB8CC!");
      if (this.onAnswersComplete) {
        this.onAnswersComplete(this.currentAnswers);
        this.onAnswersComplete = null;
      }
      return;
    }
    const question = this.currentQuestions[this.currentQuestionIndex];
    const qNum = this.currentQuestionIndex + 1;
    const total = this.currentQuestions.length;
    this.log("question", `Q${qNum}/${total}: ${question.text}`);
    this.inputContainer.empty();
    this.inputContainer.style.display = "flex";
    const inputWrapper = this.inputContainer.createEl("div", { cls: "ana-input-wrapper" });
    inputWrapper.createEl("span", {
      text: `A${qNum}: `,
      cls: "ana-input-label"
    });
    const input = inputWrapper.createEl("input", {
      type: "text",
      cls: "ana-input",
      attr: { placeholder: "\uB2F5\uBCC0 \uC785\uB825 (Enter\uB85C \uC81C\uCD9C, \uBE48 \uAC12\uC73C\uB85C \uC2A4\uD0B5)" }
    });
    input.focus();
    const submitBtn = this.inputContainer.createEl("button", {
      text: "\u2192",
      cls: "ana-btn ana-btn-primary ana-btn-sm"
    });
    const submitAnswer = () => {
      const answer = input.value.trim();
      this.currentAnswers[this.currentQuestionIndex] = answer;
      if (answer) {
        this.log("answer", `A${qNum}: ${answer}`);
      } else {
        this.log("answer", `A${qNum}: (\uC2A4\uD0B5\uB428)`);
      }
      this.currentQuestionIndex++;
      this.showNextQuestion();
    };
    input.addEventListener("keydown", (e) => {
      if (e.key === "Enter") {
        submitAnswer();
      }
    });
    submitBtn.addEventListener("click", submitAnswer);
    const skipBtn = this.inputContainer.createEl("button", {
      text: "Skip All",
      cls: "ana-btn ana-btn-sm"
    });
    skipBtn.addEventListener("click", () => {
      this.currentQuestionIndex = this.currentQuestions.length;
      this.log("info", "\uB098\uBA38\uC9C0 \uC9C8\uBB38 \uC2A4\uD0B5\uB428");
      this.showNextQuestion();
    });
  }
  /**
   * Show draft note preview
   */
  async showPreview(draft) {
    return new Promise((resolve) => {
      this.log("info", "\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501");
      this.log("preview", `\u{1F4DD} \uC0DD\uC131\uB41C \uB178\uD2B8: ${draft.title}`);
      this.log("info", "\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501");
      const previewDiv = this.logContainer.createEl("div", { cls: "ana-preview-inline" });
      if (Object.keys(draft.frontmatter).length > 0) {
        const fmDiv = previewDiv.createEl("div", { cls: "ana-fm-preview" });
        fmDiv.createEl("code", { text: "---\n" + JSON.stringify(draft.frontmatter, null, 2) + "\n---" });
      }
      const contentPreview = draft.content.length > 500 ? draft.content.substring(0, 500) + "..." : draft.content;
      previewDiv.createEl("pre", { text: contentPreview, cls: "ana-content-preview-text" });
      this.inputContainer.empty();
      this.inputContainer.style.display = "flex";
      const saveBtn = this.inputContainer.createEl("button", {
        text: "\u{1F4BE} Save",
        cls: "ana-btn ana-btn-primary"
      });
      saveBtn.addEventListener("click", () => {
        this.inputContainer.style.display = "none";
        resolve("save");
      });
      const editBtn = this.inputContainer.createEl("button", {
        text: "\u270F\uFE0F Edit in Obsidian",
        cls: "ana-btn"
      });
      editBtn.addEventListener("click", () => {
        this.inputContainer.style.display = "none";
        resolve("edit");
      });
      const cancelBtn = this.inputContainer.createEl("button", {
        text: "Cancel",
        cls: "ana-btn"
      });
      cancelBtn.addEventListener("click", () => {
        this.inputContainer.style.display = "none";
        resolve("cancel");
      });
      this.logContainer.scrollTop = this.logContainer.scrollHeight;
    });
  }
  /**
   * Show processing status
   */
  showProcessing(message) {
    this.log("info", `\u23F3 ${message}...`);
  }
  /**
   * Show success message
   */
  showSuccess(message) {
    this.log("success", message);
  }
  /**
   * Show error message
   */
  showError(message) {
    this.log("error", message);
  }
};

// main.ts
var ANAPlugin = class extends import_obsidian3.Plugin {
  constructor() {
    super(...arguments);
    this.currentSessionId = null;
    this.sidebarView = null;
  }
  async onload() {
    await this.loadSettings();
    this.apiClient = new ANAApiClient(this.settings.serverUrl);
    this.registerView(
      VIEW_TYPE_ANA,
      (leaf) => {
        this.sidebarView = new ANASidebarView(leaf, this);
        return this.sidebarView;
      }
    );
    this.addRibbonIcon("brain", "Open ANA Panel", async () => {
      await this.activateSidebar();
    });
    this.addCommand({
      id: "open-sidebar",
      name: "Open ANA Panel",
      callback: async () => {
        await this.activateSidebar();
      }
    });
    this.addCommand({
      id: "process-current-note",
      name: "Process Current Note",
      editorCallback: async (editor, view) => {
        await this.activateSidebar();
        await this.processCurrentNote();
      }
    });
    this.addCommand({
      id: "process-selection",
      name: "Process Selected Text",
      editorCallback: async (editor, view) => {
        const selection = editor.getSelection();
        if (selection) {
          await this.activateSidebar();
          await this.processContent(selection, "Selection");
        } else {
          new import_obsidian3.Notice("No text selected");
        }
      }
    });
    this.addCommand({
      id: "check-server",
      name: "Check Server Connection",
      callback: async () => {
        await this.checkServerConnection();
      }
    });
    this.addSettingTab(new ANASettingTab(this.app, this));
    this.app.workspace.onLayoutReady(() => {
      this.initLeaf();
    });
  }
  onunload() {
    if (this.currentSessionId) {
      this.apiClient.deleteSession(this.currentSessionId);
    }
    this.app.workspace.detachLeavesOfType(VIEW_TYPE_ANA);
  }
  initLeaf() {
    if (this.app.workspace.getLeavesOfType(VIEW_TYPE_ANA).length === 0) {
    }
  }
  async activateSidebar() {
    const leaves = this.app.workspace.getLeavesOfType(VIEW_TYPE_ANA);
    if (leaves.length === 0) {
      const leaf = this.app.workspace.getRightLeaf(false);
      if (leaf) {
        await leaf.setViewState({
          type: VIEW_TYPE_ANA,
          active: true
        });
      }
    }
    const activeLeaf = this.app.workspace.getLeavesOfType(VIEW_TYPE_ANA)[0];
    if (activeLeaf) {
      this.app.workspace.revealLeaf(activeLeaf);
      this.sidebarView = activeLeaf.view;
    }
  }
  async loadSettings() {
    this.settings = Object.assign({}, DEFAULT_SETTINGS, await this.loadData());
  }
  async saveSettings() {
    await this.saveData(this.settings);
    this.apiClient = new ANAApiClient(this.settings.serverUrl);
  }
  async checkServerConnection() {
    const isConnected = await this.apiClient.checkStatus();
    if (this.sidebarView) {
      if (isConnected) {
        this.sidebarView.showSuccess("ANA \uC11C\uBC84 \uC5F0\uACB0\uB428");
      } else {
        this.sidebarView.showError('\uC11C\uBC84\uC5D0 \uC5F0\uACB0\uD560 \uC218 \uC5C6\uC2B5\uB2C8\uB2E4. "ana serve" \uC2E4\uD589 \uD544\uC694');
      }
    } else {
      new import_obsidian3.Notice(isConnected ? "\u2705 ANA server is running" : "\u274C Cannot connect to ANA server");
    }
  }
  async processCurrentNote() {
    let activeView = this.app.workspace.getActiveViewOfType(import_obsidian3.MarkdownView);
    if (!activeView) {
      const leaves = this.app.workspace.getLeavesOfType("markdown");
      for (const leaf of leaves) {
        if (leaf.view instanceof import_obsidian3.MarkdownView) {
          activeView = leaf.view;
          break;
        }
      }
    }
    if (!activeView) {
      if (this.sidebarView) {
        this.sidebarView.showError("\uC5F4\uB9B0 \uB9C8\uD06C\uB2E4\uC6B4 \uB178\uD2B8\uAC00 \uC5C6\uC2B5\uB2C8\uB2E4. Obsidian\uC5D0\uC11C \uB178\uD2B8\uB97C \uBA3C\uC800 \uC5F4\uC5B4\uC8FC\uC138\uC694.");
      } else {
        new import_obsidian3.Notice("No active markdown note");
      }
      return;
    }
    const content = activeView.editor.getValue();
    const file = activeView.file;
    const title = (file == null ? void 0 : file.basename) || "Untitled";
    await this.processContent(content, title);
  }
  async processContent(content, title) {
    if (!this.sidebarView) {
      await this.activateSidebar();
    }
    const view = this.sidebarView;
    if (!view) {
      new import_obsidian3.Notice("Failed to open ANA panel");
      return;
    }
    const isConnected = await this.apiClient.checkStatus();
    if (!isConnected) {
      view.showError('ANA \uC11C\uBC84\uAC00 \uC2E4\uD589 \uC911\uC774\uC9C0 \uC54A\uC2B5\uB2C8\uB2E4. \uD130\uBBF8\uB110\uC5D0\uC11C "ana serve" \uC2E4\uD589');
      return;
    }
    view.showProcessing(`"${title}" \uCC98\uB9AC \uC911`);
    try {
      const response = await this.apiClient.processNote(content, void 0, title);
      this.currentSessionId = response.session_id;
      const topics = await view.showAnalysis(response);
      if (topics.length === 0) {
        await this.handleResponse(response, view);
      } else {
        let currentResponse = response;
        for (let i = 0; i < topics.length; i++) {
          const topic = topics[i];
          view.log("info", `
\u{1F4DD} \uC8FC\uC81C ${i + 1}/${topics.length}: ${topic}`);
          await this.handleResponse(currentResponse, view);
          if (i < topics.length - 1) {
            const nextTopic = topics[i + 1];
            const remaining = topics.length - i - 1;
            const shouldContinue = await view.askContinueWithNextTopic(nextTopic, remaining);
            if (!shouldContinue) {
              view.log("info", "\uBD84\uB9AC \uCC98\uB9AC\uAC00 \uC911\uB2E8\uB418\uC5C8\uC2B5\uB2C8\uB2E4.");
              break;
            }
            view.showProcessing(`"${nextTopic}" \uCC98\uB9AC \uC911`);
            currentResponse = await this.apiClient.processNote(content, void 0, nextTopic);
            this.currentSessionId = currentResponse.session_id;
          }
        }
        view.showSuccess("\u{1F389} \uBD84\uB9AC \uCC98\uB9AC \uC644\uB8CC!");
      }
    } catch (error) {
      view.showError(`\uC624\uB958: ${error.message}`);
      this.currentSessionId = null;
    }
  }
  async handleResponse(response, view) {
    if (response.status === "needs_info" && response.questions.length > 0) {
      const answers = await view.askQuestions(response.questions);
      view.showProcessing("\uB2F5\uBCC0 \uCC98\uB9AC \uC911");
      try {
        const newResponse = await this.apiClient.answerQuestions(
          this.currentSessionId,
          answers
        );
        await this.handleResponse(newResponse, view);
      } catch (error) {
        view.showError(`\uC624\uB958: ${error.message}`);
        this.cleanupSession();
      }
    } else if (response.status === "completed" && response.draft_note) {
      const action = await view.showPreview(response.draft_note);
      if (action === "save") {
        await this.saveNoteViaAPI(view);
      } else if (action === "edit") {
        await this.createNoteInObsidian(response.draft_note, view);
      } else {
        view.log("info", "\uCDE8\uC18C\uB428");
        this.cleanupSession();
      }
    }
  }
  async saveNoteViaAPI(view) {
    if (!this.currentSessionId) return;
    try {
      const result = await this.apiClient.saveNote(this.currentSessionId);
      if (result.success) {
        view.showSuccess(`\uB178\uD2B8 \uC800\uC7A5\uB428: ${result.path}`);
      } else {
        view.showError(`\uC800\uC7A5 \uC2E4\uD328: ${result.message}`);
      }
    } catch (error) {
      view.showError(`\uC800\uC7A5 \uC624\uB958: ${error.message}`);
    } finally {
      this.cleanupSession();
    }
  }
  async createNoteInObsidian(draftNote, view) {
    try {
      let content = "";
      if (Object.keys(draftNote.frontmatter).length > 0) {
        content += "---\n";
        for (const [key, value] of Object.entries(draftNote.frontmatter)) {
          if (Array.isArray(value)) {
            content += `${key}:
`;
            value.forEach((v) => content += `  - ${v}
`);
          } else {
            content += `${key}: ${value}
`;
          }
        }
        content += "---\n\n";
      }
      content += draftNote.content;
      const fileName = `${draftNote.title}.md`;
      const file = await this.app.vault.create(fileName, content);
      await this.app.workspace.getLeaf().openFile(file);
      view.showSuccess(`Obsidian\uC5D0 \uC0DD\uC131\uB428: ${fileName}`);
    } catch (error) {
      if (error.message.includes("already exists")) {
        view.showError(`\uD30C\uC77C\uC774 \uC774\uBBF8 \uC874\uC7AC\uD569\uB2C8\uB2E4: ${draftNote.title}.md`);
      } else {
        view.showError(`\uD30C\uC77C \uC0DD\uC131 \uC624\uB958: ${error.message}`);
      }
    } finally {
      this.cleanupSession();
    }
  }
  cleanupSession() {
    if (this.currentSessionId) {
      this.apiClient.deleteSession(this.currentSessionId);
      this.currentSessionId = null;
    }
  }
};
